features:
  node_user_picture: false
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: sites/default/ico/logo.svg
favicon:
  use_default: false
  path: sites/default/ico/favicon.ico
  mimetype: image/vnd.microsoft.icon
